import express from "express";
import path from "node:path";
import { fileURLToPath } from "node:url";
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express(); const PORT=process.env.PORT||3000; const MODEL=process.env.GEMINI_MODEL||"gemini-3.8-flash";
app.use(express.json({limit:"1mb"})); app.use(express.static(path.join(__dirname,"public")));
const SYSTEM="You are YAZONI CONTENT BRAIN, a high-standard Minecraft YouTube strategist for a solo creator. Never require friends or another human. Create specific, recordable concepts for an English-speaking Minecraft creator who likes funny, chaotic, PvP, survival, trolling and challenge content. Ideas must have a clear premise, hook, escalation, clip moments and payoff. Avoid generic AI-slop, empty title swaps, repetitive 100 Days concepts, fake virality claims, expensive requirements and anything unsafe. Prefer vanilla Minecraft or common mods/datapacks. The creator must be able to record alone. Return JSON only when requested.";
function parseJSON(t){const s=String(t||"").replace(/^\s*\`\`\`(?:json)?\s*/i,"").replace(/\s*\`\`\`\s*$/i,"").trim();const a=s.indexOf("{"),b=s.lastIndexOf("}");if(a<0||b<=a)throw Error("Model did not return valid JSON.");return JSON.parse(s.slice(a,b+1));}
async function ask(prompt){if(!process.env.GEMINI_API_KEY){const e=Error("GEMINI_API_KEY is not configured.");e.status=503;throw e;}const r=await fetch("https://generativelanguage.googleapis.com/v1beta/models/"+encodeURIComponent(MODEL)+":generateContent",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":process.env.GEMINI_API_KEY},body:JSON.stringify({system_instruction:{parts:[{text:SYSTEM}]},contents:[{role:"user",parts:[{text:prompt}]}],generationConfig:{responseMimeType:"application/json",maxOutputTokens:5000}})});const d=await r.json();if(!r.ok){const e=Error(d?.error?.message||"Gemini request failed.");e.status=r.status;throw e;}const t=d?.candidates?.[0]?.content?.parts?.map(x=>x.text||"").join("")||"";return parseJSON(t);}
function profile(p={}){return JSON.stringify({minecraftVersion:p.minecraftVersion||"1.21.x",format:p.formats||"Both",style:p.style||"Funny + chaotic",difficulty:p.difficulty||"Medium",mods:p.availableMods||"",length:p.targetLength||"5-12 minutes",restrictions:p.restrictions||"Solo only. No friends required."});}
app.get("/api/health",(_,res)=>res.json({ok:true,configured:!!process.env.GEMINI_API_KEY,model:MODEL}));
app.post("/api/generate",async(req,res)=>{try{const p=req.body||{};res.json(await ask("Create ONE exceptional Minecraft video concept. Profile: "+profile(p.profile)+" Mood: "+(p.mood||"surprise")+"\nAvoid these recent ideas: "+JSON.stringify((p.history||[]).slice(-40))+"\nReturn JSON exactly: {title,oneSentence,hook,whyItWorks,difficulty,format,setup:[...],rules:[...],recordingPlan:[...],escalation:[...],ending,clipMoments:[...],requirements:[...],thumbnailConcept,tags:[...]}. Make it specific and genuinely recordable alone."));}catch(e){res.status(e.status||500).json({error:e.message});}});
app.post("/api/improve",async(req,res)=>{try{const p=req.body||{};res.json(await ask("Rebuild this Minecraft concept, not just the title. Existing: "+JSON.stringify(p.idea)+" Profile: "+profile(p.profile)+" Instruction: "+(p.instruction||"make it crazier")+"\nReturn the same complete JSON shape: title,oneSentence,hook,whyItWorks,difficulty,format,setup,rules,recordingPlan,escalation,ending,clipMoments,requirements,thumbnailConcept,tags."));}catch(e){res.status(e.status||500).json({error:e.message});}});
app.post("/api/remix",async(req,res)=>{try{const p=req.body||{};res.json(await ask("Create a substantially different Minecraft concept from this one. Original: "+JSON.stringify(p.idea)+" Profile: "+profile(p.profile)+" Change the mechanic, story and escalation while keeping the entertainment value. Return the complete idea JSON shape."));}catch(e){res.status(e.status||500).json({error:e.message});}});
app.post("/api/build",async(req,res)=>{try{const p=req.body||{};res.json(await ask("Turn this concept into a complete practical recording blueprint. Concept: "+JSON.stringify(p.idea)+" Profile: "+profile(p.profile)+" Return JSON: {coldOpen:{visual,voiceover,durationSeconds},prep:[...],beats:[{name,goal,shot,voiceover,success}],failStates:[...],editingNotes:[...],voiceoverOutline:[...],ending:{setup,payoff,lastLine},recordingChecklist:[...],estimatedRecordingMinutes}. Make it usable while actually playing Minecraft."));}catch(e){res.status(e.status||500).json({error:e.message});}});
app.get("*",(_,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log("Yazoni Content Brain running on "+PORT));
